### ISSUE TITLE
AUC calculation

### ISSUE THREAD

**Issue by javadmozaffari** [ControlNet/LAV-DF#11]
Hello,

I have thoroughly reviewed your GitHub repository and noticed that there is no corresponding code available for calculating the AUC. I would like to kindly request if it would be possible for you to provide the code for calculating AUC in your repository. If the AUC code is not currently available, I would like to propose developing and contributing it via a pull request.

**Comment by ControlNet** [comment]
Sorry for the late reply.

Actually the temporal localization is the part we hope to address rather than classification so we didn't provide this parts in the code. For AUC, I believe it is a simple video classification problem so it can be easily evaluated.

The metrics calculation use the `AUROC` from `torchmetrics`.

Welcome for any PR contributions.
