### ISSUE TITLE
classification results

### ISSUE THREAD

**Issue by mowen9** [ControlNet/LAV-DF#16]
Congratulations on your excellent work!

I didn't find the code for the classification results and AUC calculation when I re-implemented your code.

Could you share this part of the code?

**Comment by ControlNet** [comment]
Thank you.

Actually the temporal localization is the part we hope to address rather than classification so we didn't provide this parts in the code. For AUC, I believe it is a simple video classification problem so it can be easily evaluated.

The metrics calculation use the `AUROC` from `torchmetrics`.

**Comment by Txr7** [comment]
@mowen9  Hi,excuse me, my friend, have you completed your work on the forged detection binary classification task?
